name: conduit
version: 3.0.11
homepage: https://github.com/conduit-dart/conduit
description: A modern HTTP server application framework, ORM and OAuth2 provider with OpenAPI 3.0 integration. Foundation for REST, RPC or GraphQL services.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  args: ^2.1.1
  analyzer: ^1.3.0
  collection: ^1.15.0
  conduit_common: 3.0.11
  conduit_config: 3.0.11
  conduit_isolate_exec: 3.0.11
  conduit_open_api: 3.0.11
  conduit_password_hash: 3.0.11
  conduit_runtime: 3.0.11
  crypto: ^3.0.0
  logging: ^1.0.0
  meta: ^1.1.5
  path: ^1.6.1
  postgres: ^2.3.1
  pub_cache: ^0.3.0
  pub_semver: ^2.0.0
  yaml: ^3.1.0
dev_dependencies: 
  http: ^0.13.0
  matcher: '>=0.12.3 <0.14.0'
  mockito: ^5.0.0
  pedantic: ^1.0.0
  settings_yaml: ^3.0.3
  test: ^1.16.5
  fs_test_agent: 
    path: ../fs_test_agent
  conduit_common_test: 
    path: ../common_test
  conduit_test: 
    path: ../test_harness
dependency_overrides: 
  conduit_codable: 
    path: ../codable
  conduit_common: 
    path: ../common
  conduit_config: 
    path: ../config
  conduit_isolate_exec: 
    path: ../isolate_exec
  conduit_open_api: 
    path: ../open_api
  conduit_password_hash: 
    path: ../password_hash
  conduit_runtime: 
    path: ../runtime
executables: 
  conduit: conduit
