language: dart
sudo: required
addons:
  postgresql: "9.6"
services:
  - postgresql
before_script:
  - psql -c 'create database conduit_test_db;' -U postgres
  - psql -c 'create user conduit_test_user with createdb;' -U postgres
  - psql -c "alter user conduit_test_user with password 'conduit!';" -U postgres
  - psql -c 'grant all on database conduit_test_db to conduit_test_user;' -U postgres
  - pub get
script: pub run test -j 1 -r expanded
branches:
  only:
    - master
